version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: production_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: devops_db
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - backend_net
  adminer:
    image: adminer:latest
    container_name: db_gui
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend_net
networks:
  backend_net:
    driver: bridge


